# Singular Value Decomposition of a Matrix

A central technique of matrix decomposition in linear algebra is the singular value decomposition (SVD) of a matrix, as can be used not only for square matrices but for all matrices, it is referred to as the <b>fundamental theorem of linear algebra</b>. SVD can be used for computation of PCA, least squares problems, multivariate analysis, image compression, and collaborative filtering method for recommender systems, computing the similarity documents

This technique is so powerful because can  be used to decompose a data matrix into singular values. 


# How to compute SVD by hand

<a href="SVD"><img src="drawing_SVD.jpg" align="center" width= 750px /></a>

Mathematically, SVD can be expressed as: 

<!--- <font size=4> --->
$$
\large{
\mathrm{A}=\mathrm{U\Sigma V}^{\mathrm{T}}
}
$$
</font>

Let us assume, we have the following matrix:
 <font size=3>   
$$
A=\left[\begin{array}{cc}
8 & 4 \\
1 & -7
\end{array}\right]
$$
</font>

### **Step 1**

Compute the transponse $A^{T}$ and $A^{T}A$.

So, we get the following matrices:

$$
A^{T} =\left[\begin{array}{cc}
8 & 1 \\
4 & -7
\end{array}\right]
$$

Hence, 
$$
\begin{aligned}
\mathrm{A}^{\mathrm{T}} \mathrm{A} &=\left[\begin{array}{cc}
8 & 1 \\
4 & -7
\end{array}\right]\left[\begin{array}{cc}
8 & 4 \\
1 & -7
\end{array}\right] \
\end{aligned}
$$

which results in:

$$
A^{T}A =\left[\begin{array}{cc}
65 & 25 \\
25 & 65
\end{array}\right]
$$

### **Step 2**

In step two, we determine the eigenvalues of $A^{T}A$ and sort them in descending order, in the absolute
sense. By then calculating the square roots, we get the singular values of matrix **$A$**.

$$
\operatorname{A^TA -\lambda = }\left[\begin{array}{cc}
65-\lambda & 25 \\
25 & 65-\lambda
\end{array}\right]=(65-\lambda)(65-\lambda)-(25)(25) = 0
$$

<br>
We then get:
$$
\lambda^{2} - 130\lambda + 3600 = 0
$$
<br>
<br>
Which results in the following eigenvalues:

$$
\lambda_{1} = 90, \lambda_{2} = 4
$$
<br>
<br>
by then taking the square root we get:

$$
\lambda_{1}=\sqrt{90}=9.4868, \lambda_{1}=\sqrt{40}=6.3245
$$

### **Step 3**

Now we need to construct a diagonal matrix $\Sigma$ by placing the singular values we found in descending order along the diagonal of our matrix $\Sigma$:

$$
\Sigma =\left[\begin{array}{cc}
9.4868 & 0 \\
0 & 6.3246
\end{array}\right]
$$
<br>
Then we compute the inverse of our matrix $\Sigma$, which can be found as follows:

Suppose we have this matrix $M$
$$
M=\left[\begin{array}{ll}
a & b \\
c & d 
\end{array}\right]
$$
then it's inverse can be computed like in the following:

$$
M^{-1}=\frac{1}{a d-b c}\left[\begin{array}{cc}
d & -b \\
-c & a
\end{array}\right]
$$
 <br>
 <br>
 
If we now transfer this to our matrix $\Sigma$, we get the subsequent equation: 

$$
\begin{aligned}
{\left[\begin{array}{ll}
9.4868 & 0 \\
0 & 6.3245
\end{array}\right]^{-1} } &=\frac{1}{9.4868 \times 6.3245-0 \times 0}\left[\begin{array}{cc}
6.3245 & 0 \\
0 & 9.4868
\end{array}\right] \\
&=0.01666661\left[\begin{array}{cc}
6.3245 & 0 \\
0 & 9.4868
\end{array}\right] \\
&=\left[\begin{array}{cc}
0.1054 & 0 \\
0 & 0.1581
\end{array}\right]
\end{aligned}
$$

### **Step 4**

Now we use the ordered eigenvalues from our step 2 and compute the eigenvectors of $A^{T}A$. We then place
these eigenvectors along the columns of a new matrix, which we call $V$ and as a last step, we compute the transpose of $V$, $V^{T}$.

Accordingly, to do this computation for our $\lambda_{1} = 90$ we get:

$$
\mathrm{A}^{\mathrm{T}}A-\mathrm{\lambda}=\left[\begin{array}{ll}
65-90 & 25 \\
25 & 65-90
\end{array}\right]=\left[\begin{array}{ll}
-25 & \phantom{-}25 \\
\phantom{-}25 & -25
\end{array}\right]
$$

then

$$
\left(\mathrm{A}^{\top} \mathrm{A}-\mathrm{\lambda}\right) \mathrm{X}_{1}=0
$$

which results in the following:

$$
\left[\begin{array}{ll}
-25 & \phantom{-}25 \\
\phantom{-}25 & -25
\end{array}\right]\left[\begin{array}{l}
x_{1} \\
x_{2}
\end{array}\right]=\left[\begin{array}{l}
0 \\
0
\end{array}\right]
$$

$$
\begin{aligned}
&-25 x_{1}+ 25 x_{2}=0 \\
&25 x_{1}+-25 x_{2}=0
\end{aligned}
$$

if we then solve our equation for $x_{2}$ = $x_{1}$, we get:

$$
x_{1}=\left[\begin{array}{l}
x_{1} \\
x_{2}
\end{array}\right]=\left[\begin{array}{c}
x_{1} \\
x_{1}
\end{array}\right]
$$

Dividing then by its length results in: 

$$
L=\sqrt{x_{1}^{2}+x_{2}^{2}}=x_{1} \sqrt{2}
$$

which leads to the equation as follows:

$$
\mathrm{x}_{\mathbf{1}}=\left[\begin{array}{c}
\mathrm{x}_{1} / \mathrm{L} \\
\mathrm{x}_{1} / \mathrm{L}
\end{array}\right]=\left[\begin{array}{c}
\frac{1}{\sqrt{2}} \\
\frac{-1}{\sqrt{2}}
\end{array}\right]=\left[\begin{array}{c}
0.7071 \\
0.7071
\end{array}\right]
$$

Following the same steps for our second value, $\lambda_{2} = 40$, we get:

$$
\mathrm{A}^{\mathrm{T}}A-\mathrm{\lambda}=\left[\begin{array}{ll}
65-40 & 25 \\
25 & 65-40
\end{array}\right]=\left[\begin{array}{ll}
25 & 25 \\
25 & 25
\end{array}\right]
$$

then

$$
\left(\mathrm{A}^{\top} \mathrm{A}-\mathrm{\lambda}\right) \mathrm{X}_{2}=0
$$

which results in the following:

$$
\left[\begin{array}{ll}
25 & 25 \\
25 & 25
\end{array}\right]\left[\begin{array}{l}
x_{1} \\
x_{2}
\end{array}\right]=\left[\begin{array}{l}
0 \\
0
\end{array}\right]
$$

$$
\begin{aligned}
&25 x_{1}+25 x_{2}=0 \\
&25 x_{1}+25 x_{2}=0
\end{aligned}
$$

if we then solve our equation for $x_{2}$ = $-x_{1}$, we get:

$$
x_{2}=\left[\begin{array}{l}
x_{1} \\
x_{2}
\end{array}\right]=\left[\begin{array}{c}
-x_{1} \\
\phantom{-}x_{1}
\end{array}\right]
$$

Dividing then by its length results in: 

$$
L=\sqrt{x_{1}^{2}+x_{2}^{2}}=x_{1} \sqrt{2}
$$

which leads to the equation as follows:

$$
\mathrm{x}_{\mathbf{2}}=\left[\begin{array}{c}
-\mathrm{x}_{1} / \mathrm{L} \\
\mathrm{x}_{1} / \mathrm{L}
\end{array}\right]=\left[\begin{array}{c}
\frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}}
\end{array}\right]=\left[\begin{array}{c}
-0.7071 \\
\phantom{-}0.7071
\end{array}\right]
$$


Which then gives us:

$$
\mathrm{V}=\left[\begin{array}{ll}
\mathrm{x}_{1} & \mathrm{x}_{2}
\end{array}\right]=\left[\begin{array}{cc}
0.7071 & -0.7071 \\
0.7071 & 0.7071
\end{array}\right]
$$

and if the take the transponse of our matrix $V$, we get:

$$
\mathrm{V}^{\mathbf{T}}=\left[\begin{array}{cc}
0.7071 & 0.7071 \\
-0.7071 & 0.7071
\end{array}\right]
$$
    

### **Step 5**

Now in our last step for our SVD computation, we need to compute matrix $U$ as $U$ = $AV\Sigma^{-1}$:

$$
U=A^{-1}=\left[\begin{array}{ll}
8 & 4 \\
1 & -7
\end{array}\right]\left[\begin{array}{cc}
0.7071 & -0.7071 \\
0.7071 & 0.7071
\end{array}\right]\left[\begin{array}{cc}
0.1054 & 0 \\
0 & 0.1581
\end{array}\right]
$$

$$
U=\mathrm{AV\Sigma}^{-1}=\left[\begin{array}{cc}
8 & 4 \\
1 & -7
\end{array}\right]\left[\begin{array}{cc}
0.0745 & -0.1118 \\
0.0745 & 0.1118
\end{array}\right]
$$

$$
U=\mathrm{AV\Sigma}^{-1}=\left[\begin{array}{ll}
0.894 & -0.4472 \\
-0.447 & -0.8944
\end{array}\right]
$$

## Proof

$$
\mathrm{A}=\mathrm{U\Sigma V}^{\top}=\left[\begin{array}{ll}
0.894 & -0.4472 \\
-0.447 & -0.8944
\end{array}\right]\left[\begin{array}{ll}
9.4868 & 0 \\
0 & 6.3245
\end{array}\right]\left[\begin{array}{ll}
0.7071 & -0.7071 \\
0.7071 & 0.7071
\end{array}\right]
$$

$$
\mathbf{A}=\mathrm{U\Sigma V}^{\boldsymbol{\top}}=\left[\begin{array}{cc}
0.894 & -0.4472 \\
-0.447 & -0.8944
\end{array}\right]\left[\begin{array}{cc}
6.7081 & 6.7081 \\
-4.4721 & 4.4721
\end{array}\right]
$$

$$
\mathrm{A}=\mathrm{U\Sigma V}^{\top}=\left[\begin{array}{cc}
7.99696452 & 3.99711828 \\
1.00132554 & -6.99836694
\end{array}\right] \approx\left[\begin{array}{cc}
8 & 4 \\
1 & -7
\end{array}\right]
$$

**Note:** The orthogonality of the matrix V and the matrix U becomes clear by considering their eigenvectors. This
can be proved by calculating the dot products between the column vectors - all dot products are
equal to zero. Alternatively, we could graph them to see that they are all orthogonal.

# Validation of computations with NumPy

In [2]:
import numpy as np
from IPython.display import display, Math


U = np.matrix([[0.894, -0.4472], [-0.447, -0.8944]])
sigma = np.matrix([[9.4868, 0], [0, 6.3245]])
V = (np.matrix([[0.7071, -0.7071], [0.7071, 0.7071]]))

display(Math(r'U: '))
print(U, )
display(Math(r'\Sigma: '))
print(sigma)
display(Math(r'V: '))
print(V)

<IPython.core.display.Math object>

[[ 0.894  -0.4472]
 [-0.447  -0.8944]]


<IPython.core.display.Math object>

[[9.4868 0.    ]
 [0.     6.3245]]


<IPython.core.display.Math object>

[[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]


In [3]:
intermediate_step = sigma.dot(V.T)
intermediate_step

matrix([[ 6.70811628,  6.70811628],
        [-4.47205395,  4.47205395]])

In [4]:
svd_proof = U.dot(intermediate_step)
svd_proof.round(0)

matrix([[ 8.,  4.],
        [ 1., -7.]])

## Compute the SVD of the following matrix:

$$
A=\left[\begin{array}{cc}
4 & 0 \\
3 & -5
\end{array}\right]
$$

###  Step 1
Compute the transponse $\mathrm{A^T}$ and $\mathrm{A^TA}$


In [9]:
# Note: numpy.matrix creates 2D arrays and has special operations like matrix multiplication *, and matrix power **,
# while numpy.array creates n-dimensional arrays and does not have  special matrix mathematics  operations,  
# need to use numpy.dot for matrix multiplication and numpy.linalg.matrix_power for matrix power.

#A = np.matrix([[4, 0], [3, -5]])
A = np.array([[4, 0], [3, -5]])
AtA = A.T.dot(A)

print(f"A:\n{A}")
print()
print(f"A^T:\n{A.T}")
print()
print(f"A^T * A:\n{AtA}")

A:
[[ 4  0]
 [ 3 -5]]

A^T:
[[ 4  3]
 [ 0 -5]]

A^T * A:
[[ 25 -15]
 [-15  25]]


### **Step 2**

In step two we determine the eigenvalues of $\mathrm{A^T}$ and construct a diagonal matrix $\Sigma$ by placing the singular values in descending order along the diagonal of $\Sigma$

In [15]:
# eigenvalues of A^TA
eigenvalues = np.linalg.eig(AtA)
print(f"eigenvalues of A^T * A:\n{eigenvalues[0]}")
print()
# singular values of A^TA
singular_values = np.sqrt(eigenvalues[0])
Sigma = np.diag(singular_values)

print(f"Singular values of A^T * A:\n{singular_values}")
print()
print(f"Singular Values Diagonal matrix Sigma:\n{Sigma}")

# Note can derreference as eigenvalues, eigenvectors = np.linalg.eig(AtA)

eigenvalues of A^T * A:
[40. 10.]

Singular values of A^T * A:
[6.32455532 3.16227766]

Singular Values Diagonal matrix Sigma:
[[6.32455532 0.        ]
 [0.         3.16227766]]


### **Step 3**

Compute the eigenvectors of $\mathrm{A^TA}$ corresponding to the found eigenvalues, and form matrix $\mathrm{V}$ with these eigenvectors as columns of a new matrix, compute the transpose $\mathrm{V^T}$.

In [16]:
V = eigenvalues[1]
Vt = V.T

print(f"V:\n{V}")
print()
print(f"V^T:\n{Vt}")

V:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

V^T:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


### **Step 4**

Form as diagonal matrix $\Sigma$ with $\mathrm{A^TA}$ singular  values along its diagonal

In [18]:
sigma = np.sqrt(eigenvalues[0])
Sigma = np.diag(sigma)

print(f"Sigma:\n{Sigma}")
print()
print(f"Sigma inverse:\n{np.linalg.inv(Sigma)}")

Sigma:
[[6.32455532 0.        ]
 [0.         3.16227766]]

Sigma inverse:
[[0.15811388 0.        ]
 [0.         0.31622777]]


### **Step 5**

Compute matrix $\mathrm{U}$ as $U$ = $AV\Sigma^{-1}$

In [19]:
U = A.dot(V).dot(np.linalg.inv(np.diag(sigma)))
print(f"U:\n{U}")

U:
[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]]


## Check

Confirm  that 
$$
\mathrm{A}=\mathrm{U\Sigma V}^{\top}


In [21]:
print(f"The matrix computed as U * Sigma * V^T:\n{U.dot(Sigma).dot(Vt)}")
print()
print(f"The original matrix A:\n{A}")

The matrix computed as U * Sigma * V^T:
[[ 4.  0.]
 [ 3. -5.]]

The original matrix A:
[[ 4  0]
 [ 3 -5]]


In [23]:
import sympy
from IPython.display import display, Math

x = sympy.symbols('x')
expr = (2*x**2 + 6) / (x**2 - 2*x + 2)**2
#expr = x / sympy.sqrt(x**2 + x + 2)
integral = sympy.integrate(expr, x)

# Convert to LaTeX and display
latex_integral = sympy.latex(integral)
display(Math(latex_integral))

<IPython.core.display.Math object>