# Egenvectors and Eigenvalues computation

* Matrix as Linear Transformation
* Determinant of a Linear Transformation
* Linear Systems
* Change of basis

* Egenvectors - non-trivial vectors which do not change directions when undergoing linear transformation by a given square matrix $\mathbf{A}:

$\mathbf{A}\vec{e} = \lambda\vec{e}$
$\mathbf{A}\vec{e} - \lambda\vec{e} = \vec{0}$
$(\mathbf{A} - \lambda\mathbf{I})\vec{e} = \vec{0}$

For $vec{e} \neq \vec{0}$ $\mathbf{A} - \lambda\mathbf{I}$ is non-invertible, implying
  $\det(\mathbf{A} - \lambda\mathbf{I}) = 0$

An nxn matrix A, corresponding to nth degree polybomial equaton with n roots has n  **eigenvalues**, not neecessarily all distinct.


In [5]:
import numpy as np

n_dim = 3

# Generate a random matrix with integer values
A = np.random.randint(low=-10, high=10, size=(n_dim, n_dim))

print(f"Matrix A\n{A}")

Matrix A
[[  1   9   4]
 [ -9   4  -4]
 [-10  -8   6]]


To  find the eigenvalues  and egenvectors  of matrix A:

$$
\mathbf{A} = \begin{bmatrix}
1 & 9 & 4 \\
-9 & 4 & -4 \\
-10 & -8 & 6 
\end{bmatrix}
$$

need to solve the characteristic equation

$\det(\mathbf{A} - \lambda\mathbf{I}) = 0$

$\det(\mathbf{A} - \lambda\mathbf{I}) = \det\left(\begin{bmatrix}
1-\lambda & 9 & 4 \\
-9 & 4-\lambda & -4 \\
-10 & -8 & 6-\lambda 
\end{bmatrix}\right) = 0$

Find the determinant  and  set  it to zero solving for $\lambda$:

$$
\begin{align*}
\det(\mathbf{A} - \lambda\mathbf{I}) 
&= (1-\lambda) \cdot ((4-\lambda) \cdot (6-\lambda) - (-4) \cdot (-8)) - 9 \cdot (-9 \cdot (6-\lambda) - (-4) \cdot (-10)) + 4 \cdot (-9 \cdot (-8) - (-10) \cdot (4-\lambda)) \\
&= \lambda^3 - 11\lambda^2 + 46\lambda - 120 = 0
\end{align*}
$$

Since $\lambda$ = 5 is a root

$$(\lambda - 5)(\lambda^2 - 6\lambda + 24) = 0$$

Solving
$\lambda^2 - 6\lambda + 24 = 0$

The roots of the equation $\lambda^2 - 6\lambda + 24 = 0$ can be found using the quadratic formula:

$$
\lambda = \frac{-(-6) \pm \sqrt{(-6)^2 - 4 \cdot 1 \cdot 24}}{2 \cdot 1}
$$

This simplifies to:

$$
\lambda = \frac{6 \pm \sqrt{36 - 96}}{2}  = 3 \pm \sqrt{15}i
$$

To find the eigenvectors that correspond to the above eigenvalues substitude in the $\det(\mathbf{A} - \lambda\mathbf{I}) = 0$


For $\lambda = 5$, solve this system of equations to find the corresponsing eigenvector

$$(\mathbf{A} - 5\mathbf{I})\mathbf{v} = 0$$


For $\lambda = 3 - \sqrt{15}i$, solve this system of equations to find the corresponsing eigenvector


$$(\mathbf{A} - (3 - \sqrt{15}i)\mathbf{I})\mathbf{v} = 0$$


For $\lambda = 3 + \sqrt{15}i$, solve this system of equations to find the corresponsing eigenvector


$$(\mathbf{A} - (3 + \sqrt{15}i)\mathbf{I})\mathbf{v} = 0$$


For $\lambda = 5$:

$$(\mathbf{A} - 5\mathbf{I})\mathbf{v} = 0$$

This gives us the system of equations:

$$
\begin{align*}
(-3 - 5)v_1 - 6v_2 + 2v_3 - 5v_4 &= 0 \\
-8v_1 - (1 - 5)v_2 + 7v_3 - 5v_4 &= 0 \\
7v_1 - 3v_2 + (6 - 5)v_3 - v_4 &= 0 \\
3v_1 + 5v_2 - 6v_3 - (1 - 5)v_4 &= 0
\end{align*}
$$

Solve with  row  reduction on  the augmented matrix $[\mathbf{A} - 5\mathbf{I} | 0]$:

$$
\begin{align*}
\mathbf{A} = \begin{bmatrix}
-4 & 9 & 4   | 0\\
-9 & -1 & -4 | 0\\
-10 & -8 & 1 | 0\\
\end{bmatrix}
\end{align*}
$$

Performing row reduction operations to obtain row-echelon form:

$$
\begin{align*}
\mathbf{A} = \begin{bmatrix}
1 & -9/4 & -1 | 0\\
0 & 1 & -23/5 | 0\\
0 & 0 & 0     | 0\\
\end{bmatrix}
\end{align*}
$$

express the eigenvector in terms of a non-zero arbitrary variable $\mathbf{x_1}$

$$
\begin{align*}
\mathbf{v} = \begin{bmatrix}
9/4x_2 + x_1\\
23/5x_1\\
x_1\\
\end{bmatrix}
\end{align*}
$$


In [7]:
# Calculate the determinant of A
det_A = np.linalg.det(A)

if det_A == 0:
    print("The determinant of A is zero. The inverse matrix does not exist.")
else:
    # Calculate the inverse matrix of A
    A_inv = np.linalg.inv(A)

# Print the determinant and inverse matrix
    print(f"Determinant of A: {det_A}")
    print("Inverse matrix of A:")
    print(A_inv)

Determinant of A: 1285.9999999999998
Inverse matrix of A:
[[-0.00622084 -0.06687403 -0.04043546]
 [ 0.07309487  0.03576983 -0.02488336]
 [ 0.08709176 -0.06376361  0.06609642]]


In [8]:
# Solve the eigensystem
eigenvalues, eigenvectors = np.linalg.eig(A)

    # Normalize the eigenvectors
normalized_eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)

# Print the eigenvalues and normalized eigenvectors
for i in range(len(eigenvalues)):
        eigenvalue = eigenvalues[i]
        eigenvector = normalized_eigenvectors[:, i]
        print(f"Eigenvalue {i+1}: {eigenvalue}")
        print(f"Normalized Eigenvector {i+1}: {eigenvector}")
        print()

Eigenvalue 1: (0.1408255294986504+10.952686147256545j)
Normalized Eigenvector 1: [-0.63043246+0.j          0.03375561-0.50821414j  0.05946275-0.58275041j]

Eigenvalue 2: (0.1408255294986504-10.952686147256545j)
Normalized Eigenvector 2: [-0.63043246+0.j          0.03375561+0.50821414j  0.05946275+0.58275041j]

Eigenvalue 3: (10.718348941002699+0j)
Normalized Eigenvector 3: [-0.05544994+0.j -0.45490363+0.j  0.88881269+0.j]

