# Egenvectors and Eigenvalues computation

* Linear Transformation - a vector function that moves around space such that the grid lines remain parallel and evenly spaced, and the origine remain fixed, i.e. preeserves collinearity:<br><br>
$\mathbf{L}(\vec{v} + \vec{w}) = \mathbf{L}(\vec{v}) + \mathbf{L}(\vec{w})$  <br>
$\mathbf{L}(c\vec{v}) = c\mathbf{L}(\vec{v})$ <br><br>
* Matrix as Linear Transformation of space, its columns represent the transformed cooridnates of the basis vectors;  all  matrix multiplications are linear transforms and all linear transforms that operate on finite dimennsional vectors can be expressed as matrices
* Determinant of a Linear Transformation
* Linear Systems
* Change of basis

* Egenvectors - non-trivial vectors which do not change directions when undergoing linear transformation by a given square matrix $\mathbf{A}:

$\mathbf{A}\vec{e} = \lambda\vec{e}$<br>
$\mathbf{A}\vec{e} - \lambda\vec{e} = \vec{0}$<br>
$(\mathbf{A} - \lambda\mathbf{I})\vec{e} = \vec{0}$<br>

For $\vec{e} \neq \vec{0}$<br>
$\mathbf{A} - \lambda\mathbf{I}$ is non-invertible, implying<br>
$\det(\mathbf{A} - \lambda\mathbf{I}) = 0$


An nxn matrix A, corresponding to nth degree polybomial equaton with n roots has n  **eigenvalues**, not neecessarily all distinct.


#### Generate a random 3x3 matrix with integer values

In [12]:
import numpy as np

n_dim = 3
A = np.random.randint(low=-5, high=5, size=(n_dim, n_dim))
print(f"Matrix A\n{A}")

Matrix A
[[-1 -3 -4]
 [-2 -5  4]
 [ 0  3  1]]


## Find Egenvalues and Egenvectors with Sympy

In [15]:
# SymPy is a  Python library for symbolic  mathematics
import sympy as sp

# Define the identity matrix
I = sp.eye(3)

# Define the symbol for eigenvalues
lamda = sp.symbols('lamda')

# Calculate the characteristic polynomial (the determinant of (A - λI))
char_poly = (A - lamda * I).det()

# Print the characteristic polynomial
print(f"The characteristic polynomial is:{char_poly} = 0")

The characteristic polynomial is: $-lamda**3 - 5*lamda**2 + 19*lamda + 35 = 0$


In [27]:
# since -7 is a factor of the characteristic equation constant term might be a root
# To perform polynomical division, we can use div() function from the sympy library

# Define the polynomials
numerator = -lamda**3 - 5*lamda**2 + 19*lamda + 35
denominator = lamda  + 7

# Perform the division
quotient, remainder = sp.div(numerator, denominator)

# Print the quotient and remainder
print(f"Quotient: {quotient}")
print(f"Remainder: {remainder}")

Quotient: -lamda**2 + 2*lamda + 5
Remainder: 0


In [28]:
# Define the equation
equation = -lamda**2 + 2*lamda + 5

# Solve the equation
solutions = sp.solve(equation, lamda)

# Print the solutions
print(f"The solutions are: {solutions}")

The solutions are: [1 - sqrt(6), 1 + sqrt(6)]


In [16]:
# Solve the characteristic polynomial
eigenvalues = sp.solve(char_poly, lamda)

# Print the eigenvalues
print(f"The eigenvalues are: {eigenvalues}")

The eigenvalues are: [-7, 1 - sqrt(6), 1 + sqrt(6)]


In [17]:
# Compute the eigenvectors
eigenvectors = A.eigenvects()

# Print the eigenvectors
for i in eigenvectors:
    eigenvalue = i[0]
    multiplicity = i[1]
    eigenvector = [v.evalf() for v in i[2]]
    print(f"Eigenvalue: {eigenvalue}, Multiplicity: {multiplicity}, Eigenvector: {eigenvector}")

Eigenvalue: -7, Multiplicity: 1, Eigenvector: [Matrix([
[-0.666666666666667],
[ -2.66666666666667],
[               1.0]])]
Eigenvalue: 1 - sqrt(6), Multiplicity: 1, Eigenvector: [Matrix([
[  3.44948974278318],
[-0.816496580927726],
[               1.0]])]
Eigenvalue: 1 + sqrt(6), Multiplicity: 1, Eigenvector: [Matrix([
[-1.44948974278318],
[0.816496580927726],
[              1.0]])]


## Find Egenvalues and Egenvectors with NumPy

In [33]:
A = np.array([[-1, -3, -4], [-2, -5, 4], [0, 3, 1]])

# Calculate the determinant of A
det_A = np.linalg.det(A)

if det_A == 0:
    print("The determinant of A is zero. The inverse matrix does not exist.")
else:
    # Calculate the inverse matrix of A
    A_inv = np.linalg.inv(A)

# Print the determinant and inverse matrix
    print(f"Determinant of A: {det_A}")
    print("Inverse matrix of A:")
    print(A_inv)

Determinant of A: 34.99999999999999
Inverse matrix of A:
[[-0.48571429 -0.25714286 -0.91428571]
 [ 0.05714286 -0.02857143  0.34285714]
 [-0.17142857  0.08571429 -0.02857143]]


In [34]:
# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

print(f"Eigenvalues of A: {eigenvalues}")

Eigenvalues of A: [-7.         -1.44948974  3.44948974]


In [35]:
# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues and eigenvectors
for i in range(len(eigenvalues)):
    print(f"Eigenvalue: {eigenvalues[i]}")
    print(f"Eigenvector: {eigenvectors[:, i]}")

Eigenvalue: -7.000000000000002
Eigenvector: [ 0.22792115  0.91168461 -0.34188173]
Eigenvalue: -1.4494897427831774
Eigenvector: [-0.93655787  0.22168389 -0.2715062 ]
Eigenvalue: 3.449489742783178
Eigenvector: [-0.74675429  0.42064618  0.51518425]


##  Find the Eigenvalues and Eigenvectors by hand

To  find the eigenvalues  and egenvectors  of matrix A:

$$
\mathbf{A} = \begin{bmatrix}
-1 & -3 & -4 \\
-2 & -5 & 4 \\
 0 & 3 & 1
\end{bmatrix}
$$

need to solve the characteristic equation

$\det(\mathbf{A} - \lambda\mathbf{I}) = 0$

$\det(\mathbf{A} - \lambda\mathbf{I}) = \det\left(\begin{bmatrix}
-1-\lambda & -3 & -4 \\
-2 & -5-\lambda &  4 \\
 0 & 3 & 1-\lambda 
\end{bmatrix}\right) = 0$

Find the determinant and set it to zero solving for $\lambda$:

$$
\begin{align*}
\det(\mathbf{A} - \lambda\mathbf{I}) 
&= (-1-\lambda) \cdot ((-5-\lambda) \cdot (1-\lambda) - (4) \cdot (3)) - 3 \cdot (-2 \cdot (1-\lambda) - (-4) \cdot (0)) + (-4) \cdot (-2 \cdot (-3) - (0) \cdot (-5-\lambda)) \\
&= -\lambda^3 - 5\lambda^2 + 19\lambda + 35 = 0
\end{align*}
$$

Since leading coeficient is -1, check factors of the constant term for roots; $\lambda$ = -7 is a root, than

$$(\lambda + 7)(-\lambda^2 + 2\lambda + 5) = 0$$

Solving
$-\lambda^2 + 2\lambda + 5 = 0$

The roots of the equation can be found using the quadratic formula:

$$
\lambda = \frac{-(2) \pm \sqrt{(2)^2 - 4 \cdot (-1) \cdot 5}}{2 \cdot (-1)}
$$

This simplifies to:

$$
\lambda = \frac{2 \pm \sqrt{24}}{2}  = 1 \pm \sqrt{6}
$$

To find the eigenvectors that correspond to the above eigenvalues substitude in the $\det(\mathbf{A} - \lambda\mathbf{I}) = 0$


$$
\begin{align*}
\det(\mathbf{A} - \lambda\mathbf{I}) 
&= (-1-\lambda) \cdot ((-5-\lambda) \cdot (1-\lambda) - (4) \cdot (3)) - (-1)^3 \cdot 3 \cdot (-2 \cdot (1-\lambda) - (-4) \cdot (0)) + (-4) \cdot (-2 \cdot (-3) - (0) \cdot (-5-\lambda)) \\
&= -\lambda^3 - 5\lambda^2 + 19\lambda + 35 = 0
\end{align*}
$$

For $\lambda = -7$, solve this system of equations to find the corresponsing eigenvector

$$(\mathbf{A} + 7\mathbf{I})\mathbf{v} = 0$$


For $\lambda =1 - \sqrt{6}$, solve this system of equations to find the corresponsing eigenvector


$$(\mathbf{A} - (1 - \sqrt{6})\mathbf{I})\mathbf{v} = 0$$


For $\lambda = 1 + \sqrt{6}$, solve this system of equations to find the corresponsing eigenvector


$$(\mathbf{A} - (1 + \sqrt{6})\mathbf{I})\mathbf{v} = 0$$


In [38]:
import sympy as sp

# Define the symbols
v1, v2, v3 = sp.symbols('v1 v2 v3')

# Define the equations
eq1 = 6*v1 - 3*v2 - 4*v3
eq2 = -2*v1 + 2*v2 + 4*v3
eq3 = 3*v2 + 8*v3

# Solve the system of equations
solution = sp.solve((eq1, eq2, eq3), (v1, v2, v3))

# Print the solution
print(f"The solution is: {solution}")

The solution is: {v1: -2*v3/3, v2: -8*v3/3}


In [30]:
# Define the matrix
A = sp.Matrix([[6, -3, -4], [-2, 2, 4], [0, 3, 8]])

# Compute the row-echelon form
rref_matrix, pivot_columns = A.rref()

# Print the row-echelon form
print(f"The row-echelon form of the matrix is:\n{rref_matrix}")

The row-echelon form of the matrix is:
Matrix([[1, 0, 2/3], [0, 1, 8/3], [0, 0, 0]])


For $\lambda = -7$:

$$(\mathbf{A} + 7\mathbf{I})\mathbf{v} = 0$$

This gives us the system of equations:

$$
\begin{align*}
(-1 + 7)v_1 - 3v_2 - 4v_3 &= 0 \\
-2v_1 + (- 5 + 7)v_2 + 4v_3 &= 0 \\
0v_1 + 3v_2 + (1 + 7)v_3 &= 0 
\end{align*}
$$

Solve with row reduction on the augmented matrix $[\mathbf{A} + 7\mathbf{I} | 0]$:

$$
\begin{align*}
\mathbf{A} = \begin{bmatrix}
6 & -3 & -4   | 0\\
-2 & 2 & 4    | 0\\
0 & 3 & 8     | 0
\end{bmatrix}
\end{align*}
$$

Performing row reduction operations to obtain row-echelon form:

$$
\begin{align*}
\mathbf{A} = \begin{bmatrix}
1 & 0 & 2/3 | 0\\
0 & 1 & 8/3 | 0\\
0 & 0 & 0   | 0
\end{bmatrix}
\end{align*}
$$

express the eigenvector in terms of a non-zero arbitrary variable $\mathbf{x}$

$$
\begin{align*}
\mathbf{v} = \begin{bmatrix}
-2/3x\\
-8/3x\\
x\\
\end{bmatrix}
\end{align*}
$$
